name: Sync Spark File to GCS

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  job_id:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'transformations/spark.py'
        destination: '${{ secrets.GCS_BUCKET_NAME }}'
        gzip: false

    - id: 'upload-filepaths'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'transformations/config/filepaths.py'
        destination: '${{ secrets.GCS_BUCKET_NAME }}'
        gzip: false

    - id: 'upload-schemas'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'transformations/config/schemas.py'
        destination: '${{ secrets.GCS_BUCKET_NAME }}'
        gzip: false

    - id: 'upload-data-flow'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'transformations/helpers/data_flow.py'
        destination: '${{ secrets.GCS_BUCKET_NAME }}'
        gzip: false

    - id: 'upload-data-cleaning'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'transformations/helpers/data_cleaning.py'
        destination: '${{ secrets.GCS_BUCKET_NAME }}'
        gzip: false